import type {
  AiProvider,
  ExplanationRequest,
  ProviderResponse,
  SqlPlan,
  SqlPlanRequest,
} from './provider.ts';
import { DATASET_TABLE } from '../analytics/duckdb.ts';

/**
 * Offline development provider.
 *
 * This is NOT a language model. It is a small keyword matcher that produces
 * real SQL against the sample schema so the whole pipeline — validation,
 * execution, charting, credits — can be exercised without provider
 * credentials.
 *
 * Every response it produces is flagged `simulated: true`, which the API
 * returns to the client and the UI renders as a visible "Demo mode" badge.
 * Nothing here is ever presented as a live AI answer.
 */

const DEMO_NOTE = '[Demo mode — generated by a local rule, not an AI model]';

interface Column {
  name: string;
  type: string;
}

function parseSchemaColumns(schemaText: string): Column[] {
  const columns: Column[] = [];
  for (const line of schemaText.split('\n')) {
    const m = /^\s{2}(\w+)\s+([A-Z]+)/.exec(line);
    if (m) columns.push({ name: m[1]!, type: m[2]!.toLowerCase() });
  }
  return columns;
}

const isNumeric = (c: Column) => ['double', 'bigint', 'integer', 'number'].includes(c.type);
const isDate = (c: Column) => ['date', 'timestamp'].includes(c.type);
const isText = (c: Column) => c.type === 'varchar' || c.type === 'string';

export class DemoProvider implements AiProvider {
  readonly id = 'demo';
  readonly simulated = true;

  async generateSqlPlan(req: SqlPlanRequest): Promise<ProviderResponse<SqlPlan>> {
    const columns = parseSchemaColumns(req.schemaText);
    const q = req.question.toLowerCase();

    const numeric = columns.filter(isNumeric);
    const text = columns.filter(isText);
    const dates = columns.filter(isDate);

    if (columns.length === 0) {
      return this.wrap({
        needsClarification: true,
        clarificationQuestion: `${DEMO_NOTE} I could not read the dataset schema. Try selecting the dataset again.`,
        sql: '',
        chartKind: 'none',
        chartTitle: '',
        chartXKey: '',
        chartYKeys: [],
        valueFormat: 'number',
      });
    }

    // Pick the measure the question mentions, else the first numeric column.
    const measure =
      numeric.find((c) => q.includes(c.name.replace(/_/g, ' ')) || q.includes(c.name)) ??
      numeric.find((c) => /revenue|sales|amount|total/.test(c.name)) ??
      numeric[0];

    // Pick the grouping dimension the question mentions.
    const dimension =
      text.find((c) => q.includes(c.name.replace(/_/g, ' ')) || q.includes(c.name)) ?? text[0];

    const wantsTrend = /trend|over time|month|monthly|by month|timeline|growth/.test(q);
    const wantsCount = /how many|count|number of/.test(q);

    // Carry a month filter forward from a follow-up like "now show only September".
    const monthNames = [
      'january', 'february', 'march', 'april', 'may', 'june',
      'july', 'august', 'september', 'october', 'november', 'december',
    ];
    const monthIndex = monthNames.findIndex((m) => q.includes(m));
    const dateCol = dates[0];
    const whereClause =
      monthIndex >= 0 && dateCol
        ? ` WHERE month(${dateCol.name}) = ${monthIndex + 1}`
        : '';

    if (wantsTrend && dateCol && measure) {
      return this.wrap({
        needsClarification: false,
        clarificationQuestion: '',
        sql: `SELECT date_trunc('month', ${dateCol.name}) AS period, SUM(${measure.name}) AS total_${measure.name} FROM ${DATASET_TABLE}${whereClause} GROUP BY 1 ORDER BY 1`,
        chartKind: 'line',
        chartTitle: `${measure.name.replace(/_/g, ' ')} over time`,
        chartXKey: 'period',
        chartYKeys: [`total_${measure.name}`],
        valueFormat: /revenue|price|amount|sales|cost/.test(measure.name) ? 'currency' : 'number',
      });
    }

    if (wantsCount && dimension) {
      return this.wrap({
        needsClarification: false,
        clarificationQuestion: '',
        sql: `SELECT ${dimension.name}, COUNT(*) AS row_count FROM ${DATASET_TABLE}${whereClause} GROUP BY 1 ORDER BY row_count DESC LIMIT 20`,
        chartKind: 'bar',
        chartTitle: `Row count by ${dimension.name.replace(/_/g, ' ')}`,
        chartXKey: dimension.name,
        chartYKeys: ['row_count'],
        valueFormat: 'number',
      });
    }

    if (dimension && measure) {
      return this.wrap({
        needsClarification: false,
        clarificationQuestion: '',
        sql: `SELECT ${dimension.name}, SUM(${measure.name}) AS total_${measure.name} FROM ${DATASET_TABLE}${whereClause} GROUP BY 1 ORDER BY total_${measure.name} DESC LIMIT 15`,
        chartKind: 'bar',
        chartTitle: `${measure.name.replace(/_/g, ' ')} by ${dimension.name.replace(/_/g, ' ')}`,
        chartXKey: dimension.name,
        chartYKeys: [`total_${measure.name}`],
        valueFormat: /revenue|price|amount|sales|cost/.test(measure.name) ? 'currency' : 'number',
      });
    }

    return this.wrap({
      needsClarification: true,
      clarificationQuestion: `${DEMO_NOTE} This offline demo handles "top N by category", "trend over time" and "count by category" questions. Which of those would you like?`,
      sql: '',
      chartKind: 'none',
      chartTitle: '',
      chartXKey: '',
      chartYKeys: [],
      valueFormat: 'number',
    });
  }

  async explain(req: ExplanationRequest): Promise<ProviderResponse<string>> {
    let preview: Record<string, unknown>[] = [];
    try {
      preview = JSON.parse(req.resultPreview) as Record<string, unknown>[];
    } catch {
      preview = [];
    }

    if (preview.length === 0) {
      return {
        value: `${DEMO_NOTE} The query ran successfully but returned no rows. Try widening the filters in your question.`,
        usage: null,
        simulated: true,
      };
    }

    const first = preview[0]!;
    const keys = Object.keys(first);
    const labelKey = keys[0]!;
    const valueKey = keys.find((k) => typeof first[k] === 'number') ?? keys[1] ?? labelKey;

    const fmt = (v: unknown) =>
      typeof v === 'number' ? v.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(v);

    const top = preview
      .slice(0, 3)
      .map((r) => `${String(r[labelKey])} (${fmt(r[valueKey])})`)
      .join(', ');

    const sentence =
      preview.length === 1
        ? `The result is ${fmt(first[valueKey])} for ${String(first[labelKey])}.`
        : `The top entries by ${valueKey.replace(/_/g, ' ')} are ${top}.`;

    return {
      value: `${DEMO_NOTE} ${sentence} The query returned ${req.rowCount.toLocaleString()} row(s). Connect an AI provider key to get a written analysis instead of this summary.`,
      usage: null,
      simulated: true,
    };
  }

  private wrap(plan: SqlPlan): ProviderResponse<SqlPlan> {
    return { value: plan, usage: null, simulated: true };
  }
}
