import { Button, Modal } from './ui.tsx';

/**
 * Shown the moment an anonymous visitor enters the demo.
 *
 * The point is to set expectations *before* the first answer rather than
 * after. A visitor who reads a confident paragraph about their data and only
 * later learns it was generated by a rule has been misled, even though every
 * answer carries a badge — nobody reads badges before they read the answer.
 *
 * It is equally careful not to undersell: the SQL, the query engine, the
 * charts and the tables are all genuinely running. Only the language model is
 * substituted. Saying "this is fake" would be as inaccurate as saying nothing.
 */
export function DemoIntroModal({
  open,
  onClose,
  onGetStarted,
  questionsLimit,
}: {
  open: boolean;
  onClose: () => void;
  onGetStarted: () => void;
  questionsLimit: number;
}) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      title="You're in demo mode"
      description="Have a look around — here is what you are actually seeing."
    >
      <div className="space-y-4">
        <div className="space-y-3 rounded-lg bg-[var(--surface-2)] p-3.5 text-sm leading-relaxed">
          <p className="text-[var(--text-secondary)]">
            <strong className="text-[var(--text-primary)]">Answers are simulated.</strong> They
            come from a simple built-in rule, not an AI model, so the wording is canned and the
            interpretation is not real analysis. Do not read anything into what it says.
          </p>
          <p className="text-[var(--text-secondary)]">
            <strong className="text-[var(--text-primary)]">Everything else is real.</strong> The
            SQL is really generated, really checked against a safety allowlist, and really run
            against the sample dataset in an isolated engine. The numbers in the tables and
            charts are genuine query results.
          </p>
          <p className="text-[var(--text-secondary)]">
            <strong className="text-[var(--text-primary)]">The demo is limited</strong> to{' '}
            {questionsLimit} questions on the sample dataset. Uploading your own data needs an
            account.
          </p>
        </div>

        <p className="text-sm text-[var(--text-secondary)]">
          Create a free account for answers from a real model, and to analyse your own CSV.
        </p>

        <div className="flex flex-wrap gap-2">
          <Button className="flex-1" onClick={onGetStarted}>
            Get real answers
          </Button>
          <Button variant="secondary" onClick={onClose}>
            Explore the demo
          </Button>
        </div>
      </div>
    </Modal>
  );
}
