import { Button, Modal } from './ui.tsx';

/**
 * The sign-in nudge shown to anonymous visitors.
 *
 * Two different things share this component, distinguished by `blocking`:
 *
 *  - **The nudge** (dismissible). Appears after a few answers and repeats.
 *    "Cancel" keeps them exploring — this is persuasion, not a wall, so it
 *    must not pretend the demo has stopped working.
 *  - **The ceiling** (not dismissible by carrying on). The server refuses
 *    further analyses past the hard limit, so offering "keep exploring" here
 *    would be a lie; the only honest action is to sign in.
 */
export function GuestNudgeModal({
  open,
  onClose,
  onSignIn,
  questionsUsed,
  questionsLimit,
  blocking,
}: {
  open: boolean;
  onClose: () => void;
  onSignIn: () => void;
  questionsUsed: number;
  questionsLimit: number;
  blocking: boolean;
}) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      // A blocking dialog should not vanish on a stray backdrop click.
      closeOnBackdrop={!blocking}
      title={blocking ? "That's the end of the demo" : 'Enjoying the demo?'}
      description={
        blocking
          ? `The demo is limited to ${questionsLimit} questions. Create a free account to keep going with real AI analysis.`
          : "You're exploring with sample answers. They show how VoiceQuery works, but they're generated by a simple rule — not an AI model."
      }
    >
      <div className="space-y-4">
        <div className="space-y-2 rounded-lg bg-[var(--surface-2)] p-3 text-sm text-[var(--text-secondary)]">
          <p className="font-medium text-[var(--text-primary)]">
            With a free account you get:
          </p>
          <ul className="space-y-1.5">
            <li className="flex gap-2">
              <span aria-hidden="true" className="text-[var(--good)]">
                ✓
              </span>
              <span>
                <strong className="text-[var(--text-primary)]">Real AI answers</strong> — actual
                analysis of your question, not a canned response
              </span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden="true" className="text-[var(--good)]">
                ✓
              </span>
              <span>
                <strong className="text-[var(--text-primary)]">Upload your own CSV</strong> and
                ask questions about your data
              </span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden="true" className="text-[var(--good)]">
                ✓
              </span>
              <span>
                <strong className="text-[var(--text-primary)]">Use your own API key</strong> for
                unlimited questions billed to your provider
              </span>
            </li>
          </ul>
        </div>

        {!blocking && (
          <p className="text-xs text-[var(--text-muted)]">
            {questionsUsed} demo question{questionsUsed === 1 ? '' : 's'} so far · you can keep
            exploring without an account
          </p>
        )}

        <div className="flex gap-2">
          {!blocking && (
            <Button variant="secondary" className="flex-1" onClick={onClose}>
              Cancel
            </Button>
          )}
          <Button className="flex-1" onClick={onSignIn}>
            OK, sign me up
          </Button>
        </div>

        {blocking && (
          <button
            type="button"
            onClick={onClose}
            className="w-full text-center text-xs text-[var(--text-muted)] hover:text-[var(--text-secondary)]"
          >
            Close and review my earlier results
          </button>
        )}
      </div>
    </Modal>
  );
}
